package com.api.glovoCRM.constants;

public enum EStatusOrderDetail {
    PRODUCT_STATUS_CREATED,
    PRODUCT_STATUS_IN_PROGRESS,
    PRODUCT_STATUS_READY_TO_DELIVER,
    PRODUCT_STATUS_DELIVERING,
    PRODUCT_STATUS_DELIVERED,
}
